[build]
  base = "inspireHope-frontend"
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_CONTACT_FORM_ENDPOINT = "https://formspree.io/f/mnjldpeg"
  VITE_PAYSTACK_PUBLIC_KEY = "pk_test_9d116dc579f2fee8f9a705b8cb30cc6c94593611"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
